#include "vll/curriculum/CurriculumCatalog.h"

#include <array>

namespace vll::curriculum {
namespace {

constexpr std::array<SourceDocumentReference, 3> kSourceDocuments{
    SourceDocumentReference{"VL-STUDY", "Voice Leading for Pianists, Volume I: Study Guide",
                            "Voice_Leading_for_Pianists_Volume_I_Study_Guide_Notation_Fixed.pdf",
                            "c6ff4d9d1e08b61ef8d80a8b647ba141861f2b788a2563475a17be832c9e30f0", 42},
    SourceDocumentReference{"VL-PRACTICE", "Voice Leading for Pianists, Volume II: Practice Companion",
                            "Voice_Leading_for_Pianists_Volume_II_Practice_Companion_Notation_Fixed.pdf",
                            "e2ad2e7071155a95ebe1fbd9896b8156c0de2a83fd7a324400400f70759587dd", 38},
    SourceDocumentReference{"BH-GUIDE", "The Moving Harmony Method: Piano Study Guide",
                            "Barry_Harris_Piano_Method_Independent_Study_Guide.pdf",
                            "bdcdb4f830b018b5e6d4f3300b564dd784a977a68e92e3904b9709f1ee677438", 83},
};

constexpr std::array<VoiceLeadingConceptReference, 64> kVoiceLeadingConcepts{
    VoiceLeadingConceptReference{"VL-01.1", "A chord is a snapshot, not a complete explanation", 1, 7, 1, 4},
    {"VL-01.2", "A voice keeps an identity through time", 1, 7, 1, 4},
    {"VL-01.3", "Minimum motion is the default economy", 1, 7, 1, 4},
    {"VL-01.4", "Hear destinations, not merely intervals", 1, 7, 1, 4},
    {"VL-02.1", "Contrary, oblique, similar, and parallel motion", 2, 9, 2, 6},
    {"VL-02.2", "Step, skip, leap, and recovery", 2, 9, 2, 6},
    {"VL-02.3", "Register, crossing, and overlap", 2, 9, 2, 6},
    {"VL-02.4", "Parallel perfect intervals are style-dependent", 2, 9, 2, 6},
    {"VL-03.1", "The leading tone as directed energy", 3, 11, 3, 7},
    {"VL-03.2", "The chordal seventh usually resolves downward", 3, 11, 3, 7},
    {"VL-03.3", "Suspension is controlled delay", 3, 11, 3, 7},
    {"VL-03.4", "Non-chord tones are linear events", 3, 11, 3, 7},
    {"VL-04.1", "Retain common tones when they serve the line", 4, 13, 4, 9},
    {"VL-04.2", "Inversions are routing options", 4, 13, 4, 9},
    {"VL-04.3", "Root motion and upper-voice motion are separate problems", 4, 13, 4, 9},
    {"VL-04.4", "Build I-IV-V-I as four melodies", 4, 13, 4, 9},
    {"VL-05.1", "Thirds and sevenths form the harmonic skeleton", 5, 15, 5, 11},
    {"VL-05.2", "The ii-V-I two-note skeleton", 5, 15, 5, 11},
    {"VL-05.3", "Add color tones without breaking the skeleton", 5, 15, 5, 11},
    {"VL-05.4", "Rootless voicings are voice-leading devices", 5, 15, 5, 11},
    {"VL-06.1", "Bass independence", 6, 17, 6, 13},
    {"VL-06.2", "Stepwise bass through inversions", 6, 17, 6, 13},
    {"VL-06.3", "Pedal points create controlled friction", 6, 17, 6, 13},
    {"VL-06.4", "Contrary bass and soprano expand the texture", 6, 17, 6, 13},
    {"VL-07.1", "Circle-of-fifths roots, stepwise upper voices", 7, 19, 7, 15},
    {"VL-07.2", "iii-VI-ii-V-I as one voice-leading sentence", 7, 19, 7, 15},
    {"VL-07.3", "Secondary dominants create temporary tendency tones", 7, 19, 7, 15},
    {"VL-07.4", "Cadences are bundles of resolutions", 7, 19, 7, 15},
    {"VL-08.1", "The line cliche", 8, 21, 8, 16},
    {"VL-08.2", "Common tones can frame moving lines", 8, 21, 8, 16},
    {"VL-08.3", "Change one voice and listen to the chord change itself", 8, 21, 8, 16},
    {"VL-08.4", "Compound inner lines", 8, 21, 8, 16},
    {"VL-09.1", "Prepared suspension: consonance, tension, release", 9, 23, 9, 18},
    {"VL-09.2", "Anticipation arrives early", 9, 23, 9, 18},
    {"VL-09.3", "Appoggiatura: accented dissonance with a destination", 9, 23, 9, 18},
    {"VL-09.4", "Rhythmic displacement can preserve the same harmonic line", 9, 23, 9, 18},
    {"VL-10.1", "Chromatic passing notes inside a voice", 10, 25, 10, 20},
    {"VL-10.2", "Diminished chords are efficient semitone machines", 10, 25, 10, 20},
    {"VL-10.3", "Tritone substitution preserves guide-tone behavior", 10, 25, 10, 20},
    {"VL-10.4", "Altered dominants are collections of destinations", 10, 25, 10, 20},
    {"VL-11.1", "Shell voicings expose the essential lines", 11, 27, 11, 22},
    {"VL-11.2", "Rootless A/B voicings are two orientations of the same network", 11, 27, 11, 22},
    {"VL-11.3", "Drop-2 and spread voicings redistribute voices, not function", 11, 27, 11, 22},
    {"VL-11.4", "Top-note control is the pianist's arranging discipline", 11, 27, 11, 22},
    {"VL-12.1", "Ninths and thirteenths should go somewhere", 12, 29, 12, 24},
    {"VL-12.2", "The 11th and #11 are different line problems", 12, 29, 12, 24},
    {"VL-12.3", "Alterations are semitone approaches to targets", 12, 29, 12, 24},
    {"VL-12.4", "Upper structures are coordinated lines, not floating triads", 12, 29, 12, 24},
    {"VL-13.1", "The melody is the soprano, not an ornament", 13, 31, 13, 26},
    {"VL-13.2", "Guide tones under the melody", 13, 31, 13, 26},
    {"VL-13.3", "Reharmonize by changing the bass first", 13, 31, 13, 26},
    {"VL-13.4", "Reharmonize by moving one inner voice", 13, 31, 13, 26},
    {"VL-14.1", "Sixth-diminished harmony is an alternating voice-leading field", 14, 33, 14, 28},
    {"VL-14.2", "Borrowing is controlled displacement of voices", 14, 33, 14, 28},
    {"VL-14.3", "Related dominants share diminished voice-leading material", 14, 33, 14, 28},
    {"VL-14.4", "Minor-sixth relationships compress ii-V movement", 14, 33, 14, 28},
    {"VL-15.1", "Modal harmony needs internal motion even when the root is static", 15, 35, 15, 29},
    {"VL-15.2", "Planing is intentional parallelism", 15, 35, 15, 29},
    {"VL-15.3", "Quartal voicings still contain voices", 15, 35, 15, 29},
    {"VL-15.4", "Chromatic mediants work through common tones and parsimonious motion", 15, 35, 15, 29},
    {"VL-16.1", "Texture has a hierarchy", 16, 37, 16, 31},
    {"VL-16.2", "Reduction reveals what the harmony is doing", 16, 37, 16, 31},
    {"VL-16.3", "Compose from soprano and bass inward", 16, 37, 16, 31},
    {"VL-16.4", "The complete analysis protocol", 16, 37, 16, 31},
};

constexpr std::array<PracticeUnitReference, 16> kPracticeUnits{
    PracticeUnitReference{"VL-U01", "Horizontal Hearing: What Voice Leading Actually Is", 1, 4,
                          {"VL-01.1", "VL-01.2", "VL-01.3", "VL-01.4"}},
    {"VL-U02", "Motion Between Voices", 2, 6, {"VL-02.1", "VL-02.2", "VL-02.3", "VL-02.4"}},
    {"VL-U03", "Tendency, Dissonance, and Resolution", 3, 7, {"VL-03.1", "VL-03.2", "VL-03.3", "VL-03.4"}},
    {"VL-U04", "Triads as Voice Networks", 4, 9, {"VL-04.1", "VL-04.2", "VL-04.3", "VL-04.4"}},
    {"VL-U05", "Seventh Chords and Guide Tones", 5, 11, {"VL-05.1", "VL-05.2", "VL-05.3", "VL-05.4"}},
    {"VL-U06", "The Bass as a Counterline", 6, 13, {"VL-06.1", "VL-06.2", "VL-06.3", "VL-06.4"}},
    {"VL-U07", "Cycles, Turnarounds, and Functional Progressions", 7, 15, {"VL-07.1", "VL-07.2", "VL-07.3", "VL-07.4"}},
    {"VL-U08", "Inner Lines and Linear Harmony", 8, 16, {"VL-08.1", "VL-08.2", "VL-08.3", "VL-08.4"}},
    {"VL-U09", "Suspensions, Anticipations, and Delayed Resolution", 9, 18, {"VL-09.1", "VL-09.2", "VL-09.3", "VL-09.4"}},
    {"VL-U10", "Chromatic Motion, Diminished Connectors, and Substitution", 10, 20, {"VL-10.1", "VL-10.2", "VL-10.3", "VL-10.4"}},
    {"VL-U11", "Jazz Voicings as Moving Structures", 11, 22, {"VL-11.1", "VL-11.2", "VL-11.3", "VL-11.4"}},
    {"VL-U12", "Extensions and Alterations as Melodic Voices", 12, 24, {"VL-12.1", "VL-12.2", "VL-12.3", "VL-12.4"}},
    {"VL-U13", "Harmonizing Melody from the Top Down", 13, 26, {"VL-13.1", "VL-13.2", "VL-13.3", "VL-13.4"}},
    {"VL-U14", "Barry Harris Through the Lens of Voice Leading", 14, 28, {"VL-14.1", "VL-14.2", "VL-14.3", "VL-14.4"}},
    {"VL-U15", "Modal, Quartal, and Constant-Structure Voice Leading", 15, 29, {"VL-15.1", "VL-15.2", "VL-15.3", "VL-15.4"}},
    {"VL-U16", "Solo Piano, Composition, and Analytical Reduction", 16, 31, {"VL-16.1", "VL-16.2", "VL-16.3", "VL-16.4"}},
};

constexpr std::array<PracticeExerciseReference, 80> kPracticeExercises{
    PracticeExerciseReference{"VL-EX-01A", "1A", "Vertical labels vs. horizontal lines", 1},
    {"VL-EX-01B", "1B", "Finger-by-finger hearing", 1},
    {"VL-EX-01C", "1C", "Minimum-motion challenge", 1},
    {"VL-EX-01D", "1D", "Destination test", 1},
    {"VL-EX-01E", "1E", "Original four-voice sentence", 1},
    {"VL-EX-02A", "2A", "Motion classification", 2}, {"VL-EX-02B", "2B", "Two-voice counterlines", 2},
    {"VL-EX-02C", "2C", "Leap and recovery", 2}, {"VL-EX-02D", "2D", "Register experiment", 2},
    {"VL-EX-02E", "2E", "Parallelism by choice", 2},
    {"VL-EX-03A", "3A", "Leading-tone map", 3}, {"VL-EX-03B", "3B", "Dominant seventh map", 3},
    {"VL-EX-03C", "3C", "Two-guide-tone cadences", 3}, {"VL-EX-03D", "3D", "Suspension laboratory", 3},
    {"VL-EX-03E", "3E", "Accented dissonance", 3},
    {"VL-EX-04A", "4A", "Common-tone triads", 4}, {"VL-EX-04B", "4B", "Inversion routing", 4},
    {"VL-EX-04C", "4C", "Root leap, upper economy", 4}, {"VL-EX-04D", "4D", "Four melodies through I-IV-V-I", 4},
    {"VL-EX-04E", "4E", "Three alternate realizations", 4},
    {"VL-EX-05A", "5A", "Guide-tone ii-V-I", 5}, {"VL-EX-05B", "5B", "Add one color tone", 5},
    {"VL-EX-05C", "5C", "Add two color tones", 5}, {"VL-EX-05D", "5D", "Soprano control", 5},
    {"VL-EX-05E", "5E", "Reduction test", 5},
    {"VL-EX-06A", "6A", "Bass as melody", 6}, {"VL-EX-06B", "6B", "Descending inversion bass", 6},
    {"VL-EX-06C", "6C", "Tonic pedal", 6}, {"VL-EX-06D", "6D", "Dominant pedal", 6},
    {"VL-EX-06E", "6E", "Outer-voice first", 6},
    {"VL-EX-07A", "7A", "Circle guide tones", 7}, {"VL-EX-07B", "7B", "Turnaround top line", 7},
    {"VL-EX-07C", "7C", "Secondary-dominant insertion", 7}, {"VL-EX-07D", "7D", "Staggered cadence", 7},
    {"VL-EX-07E", "7E", "Twelve-key cycle", 7},
    {"VL-EX-08A", "8A", "Minor line cliche", 8}, {"VL-EX-08B", "8B", "Major line cliche", 8},
    {"VL-EX-08C", "8C", "One-voice discovery", 8}, {"VL-EX-08D", "8D", "Fixed soprano reharm", 8},
    {"VL-EX-08E", "8E", "Two inner lines", 8},
    {"VL-EX-09A", "9A", "Prepared suspension", 9}, {"VL-EX-09B", "9B", "Anticipation", 9},
    {"VL-EX-09C", "9C", "Appoggiatura", 9}, {"VL-EX-09D", "9D", "Displaced guide tones", 9},
    {"VL-EX-09E", "9E", "Comping study", 9},
    {"VL-EX-10A", "10A", "Chromatic passing line", 10}, {"VL-EX-10B", "10B", "Diminished connector", 10},
    {"VL-EX-10C", "10C", "Tritone substitution", 10}, {"VL-EX-10D", "10D", "Backward altered dominant", 10},
    {"VL-EX-10E", "10E", "Chromatic chain", 10},
    {"VL-EX-11A", "11A", "Shell-only blues", 11}, {"VL-EX-11B", "11B", "Rootless A/B forms", 11},
    {"VL-EX-11C", "11C", "Drop-2 conversion", 11}, {"VL-EX-11D", "11D", "Top-note matrix", 11},
    {"VL-EX-11E", "11E", "Register discipline", 11},
    {"VL-EX-12A", "12A", "Color-tone line", 12}, {"VL-EX-12B", "12B", "#11 destinations", 12},
    {"VL-EX-12C", "12C", "Alteration target map", 12}, {"VL-EX-12D", "12D", "Upper-structure resolution", 12},
    {"VL-EX-12E", "12E", "Less is more", 12},
    {"VL-EX-13A", "13A", "Top-down harmonization", 13}, {"VL-EX-13B", "13B", "Guide-tone support", 13},
    {"VL-EX-13C", "13C", "Bass reinterpretation", 13}, {"VL-EX-13D", "13D", "One-inner-voice reharm", 13},
    {"VL-EX-13E", "13E", "Two reharmonizations", 13},
    {"VL-EX-14A", "14A", "Sixth-diminished four lines", 14}, {"VL-EX-14B", "14B", "Borrow one note", 14},
    {"VL-EX-14C", "14C", "Borrow two notes", 14},
    {"VL-EX-14D", "14D", "Four dominants, one diminished upper structure", 14},
    {"VL-EX-14E", "14E", "Minor-sixth over dominant bass", 14},
    {"VL-EX-15A", "15A", "Modal upper motion", 15}, {"VL-EX-15B", "15B", "Diatonic planing", 15},
    {"VL-EX-15C", "15C", "Chromatic planing", 15}, {"VL-EX-15D", "15D", "Quartal top-line control", 15},
    {"VL-EX-15E", "15E", "Chromatic mediants", 15},
    {"VL-EX-16A", "16A", "Reduction", 16}, {"VL-EX-16B", "16B", "Reconstruction", 16},
    {"VL-EX-16C", "16C", "Outer-voice composition", 16}, {"VL-EX-16D", "16D", "Six-pass analysis", 16},
    {"VL-EX-16E", "16E", "Cumulative etude", 16},
};

constexpr std::array<PracticeEtudeReference, 12> kPracticeEtudes{
    PracticeEtudeReference{"VL-ETUDE-01", "Two Lines, No Chords", 34},
    {"VL-ETUDE-02", "Common-Tone Triads", 34}, {"VL-ETUDE-03", "Guide-Tone Sentence", 34},
    {"VL-ETUDE-04", "Descending Bass", 34}, {"VL-ETUDE-05", "Inner Chromatic Line", 34},
    {"VL-ETUDE-06", "Suspension Study", 34}, {"VL-ETUDE-07", "Diminished Bridge", 34},
    {"VL-ETUDE-08", "Altered Resolution", 35}, {"VL-ETUDE-09", "Rootless Comping", 35},
    {"VL-ETUDE-10", "Barry Field", 35}, {"VL-ETUDE-11", "Modal Color", 35},
    {"VL-ETUDE-12", "Integrated Solo Texture", 35},
};

constexpr std::array<BarryChapterReference, 33> kBarryChapters{
    BarryChapterReference{"BH-CH-01", "Movement Before Chord Symbols", 1, 5},
    {"BH-CH-02", "The Major Sixth-Diminished Scale", 1, 6},
    {"BH-CH-03", "The Minor Sixth-Diminished Scale", 1, 7},
    {"BH-CH-04", "Piano Inversions, Register, and Small Chords", 1, 8},
    {"BH-CH-05", "Harmonizing a Melody Note by Note", 1, 9},
    {"BH-CH-06", "Borrowed Diminished Notes", 1, 10},
    {"BH-CH-07", "Contrary Motion and Independent Voices", 1, 11},
    {"BH-CH-08", "The Diminished Chord and Four Related Dominants", 2, 13},
    {"BH-CH-09", "Major-Sixth and Minor-Seventh Equivalence", 2, 14},
    {"BH-CH-10", "Minor-Sixth and Half-Diminished Equivalence", 2, 15},
    {"BH-CH-11", "The Important Minor and the Tritone's Minor", 2, 15},
    {"BH-CH-12", "Thinking Sixth-Sixth-Sixth Through a II-V-I", 2, 17},
    {"BH-CH-13", "Dominant-Seventh Diminished Scales", 2, 18},
    {"BH-CH-14", "Passing Diminished Chords and the bIII Diminished", 2, 18},
    {"BH-CH-15", "Scale Practice as the ABCs", 3, 20},
    {"BH-CH-16", "Extra Notes and Rhythmic Alignment", 3, 21},
    {"BH-CH-17", "Dominant, Major, and Minor Line Rules", 3, 21},
    {"BH-CH-18", "The Chromatic Scale as Organized Material", 3, 23},
    {"BH-CH-19", "The 5-4-3-2 Framework", 3, 23},
    {"BH-CH-20", "Surrounding Notes, Approaches, and Turnbacks", 3, 24},
    {"BH-CH-21", "Feeling Six While Playing Four", 3, 25},
    {"BH-CH-22", "Comping: Two Hands, Three Textures", 4, 27},
    {"BH-CH-23", "Solo Piano and Melody Harmonization", 4, 28},
    {"BH-CH-24", "The Blues", 4, 28},
    {"BH-CH-25", "Rhythm Changes", 4, 29},
    {"BH-CH-26", "Bridges, Cycles, and Fast-Moving Standards", 4, 30},
    {"BH-CH-27", "Ballads and Harmonic Movement", 4, 31},
    {"BH-CH-28", "Building an Original Chorus", 4, 32},
    {"BH-CH-29", "Twelve-Week Practice Course", 5, 33},
    {"BH-CH-30", "Tests, Troubleshooting, and Continuing Study", 5, 34},
    {"BH-CH-31", "Twenty-Four Key Laboratories", 5, 35},
    {"BH-CH-32", "II-V-I Progression Laboratories", 5, 59},
    {"BH-CH-33", "Eight Original Piano Etudes", 5, 65},
};

constexpr std::array<BarryAppendixReference, 5> kBarryAppendices{
    BarryAppendixReference{"BH-APP-A", "Major Sixth-Diminished Scales in Twelve Keys", 74},
    {"BH-APP-B", "Minor Sixth-Diminished Scales in Twelve Keys", 77},
    {"BH-APP-C", "Related Dominant Families", 80},
    {"BH-APP-D", "II-V-I Piano Roadmaps", 81},
    {"BH-APP-E", "Glossary and Sources", 82},
};

constexpr std::array<BenchmarkReference, 5> kBenchmarkMapping{
    BenchmarkReference{0, "Unknown", "Not Started"},
    {1, "Recognized", "Introduced"},
    {2, "Controlled", "Developing"},
    {3, "Transferable", "Reliable"},
    {4, "Musical", "Fluent"},
};

} // namespace

std::span<const SourceDocumentReference> CurriculumCatalog::sourceDocuments() { return kSourceDocuments; }
std::span<const VoiceLeadingConceptReference> CurriculumCatalog::voiceLeadingConcepts() { return kVoiceLeadingConcepts; }
std::span<const PracticeUnitReference> CurriculumCatalog::practiceUnits() { return kPracticeUnits; }
std::span<const PracticeExerciseReference> CurriculumCatalog::practiceExercises() { return kPracticeExercises; }
std::span<const PracticeEtudeReference> CurriculumCatalog::practiceEtudes() { return kPracticeEtudes; }
std::span<const BarryChapterReference> CurriculumCatalog::barryChapters() { return kBarryChapters; }
std::span<const BarryAppendixReference> CurriculumCatalog::barryAppendices() { return kBarryAppendices; }
std::span<const BenchmarkReference> CurriculumCatalog::benchmarkMapping() { return kBenchmarkMapping; }

} // namespace vll::curriculum
