#include "vll/barry/BarryHarrisEngine.h"
#include <algorithm>
#include <set>
namespace vll::barry { namespace { int pc(int n){n%=12;return n<0?n+12:n;} }
BarryField BarryHarrisEngine::field(int key,bool minor) const { key=pc(key); BarryField f; f.key=key;f.minor=minor;f.sixth={key,pc(key+(minor?3:4)),pc(key+7),pc(key+9)};f.diminished={pc(key+2),pc(key+5),pc(key+8),pc(key+11)};f.collection=f.sixth;f.collection.insert(f.collection.end(),f.diminished.begin(),f.diminished.end());std::ranges::sort(f.collection);return f; }
SixthFamily BarryHarrisEngine::classify(const Sonority& v,const BarryField& f) const { bool s=true,d=true;for(auto p:v.pitches){s&=std::ranges::find(f.sixth,p.pitchClass())!=f.sixth.end();d&=std::ranges::find(f.diminished,p.pitchClass())!=f.diminished.end();}return s?(f.minor?SixthFamily::Minor:SixthFamily::Major):d?SixthFamily::Diminished:SixthFamily::Diminished; }
std::vector<Sonority> BarryHarrisEngine::inversions(const BarryField& f,Pitch melody,int voices) const {std::vector<Sonority> out;if(voices<2||voices>4||std::ranges::find(f.collection,melody.pitchClass())==f.collection.end())return out;const auto& family=std::ranges::find(f.sixth,melody.pitchClass())!=f.sixth.end()?f.sixth:f.diminished;for(int low=36;low<melody.midiNote;++low){if(std::ranges::find(family,Pitch{low}.pitchClass())==family.end())continue;Sonority s;for(int n=low;n<melody.midiNote&&static_cast<int>(s.pitches.size())<voices-1;++n)if(std::ranges::find(family,Pitch{n}.pitchClass())!=family.end())s.pitches.push_back({n});if(static_cast<int>(s.pitches.size())==voices-1){s.pitches.push_back(melody);out.push_back(s);}}return out; }
BorrowedVoicing BarryHarrisEngine::borrow(const Sonority& pure,const BarryField& f,int count) const {BorrowedVoicing r{pure,pure,{}};count=std::clamp(count,0,static_cast<int>(pure.pitches.size()));for(int i=0;i<count;++i){auto& p=r.borrowed.pitches[static_cast<std::size_t>(i)];int best=p.midiNote,bestD=99;for(int n=p.midiNote-2;n<=p.midiNote+2;++n)if(std::ranges::find(f.diminished,Pitch{n}.pitchClass())!=f.diminished.end()&&std::abs(n-p.midiNote)<bestD){best=n;bestD=std::abs(n-p.midiNote);}p={best};r.borrowedVoices.push_back(static_cast<VoiceId>(i+1));}std::ranges::sort(r.borrowed.pitches);return r; }
std::vector<int> BarryHarrisEngine::relatedDominantRoots(const BarryField& f) const {std::vector<int> r;for(int tone:f.diminished)r.push_back(pc(tone-4));std::ranges::sort(r);return r;}
Sonority BarryHarrisEngine::reinterpretMinorSixOverBass(int root,Pitch bass) const {root=pc(root);Sonority s;s.pitches={bass,Pitch{48+root},Pitch{48+pc(root+3)},Pitch{48+pc(root+7)},Pitch{48+pc(root+9)}};std::ranges::sort(s.pitches);return s;}
}
