#include "vll/release/ReleaseReadiness.h"
#include <charconv>
#include <sstream>
namespace vll::release {
bool ReleaseReadiness::validateAccessibility(const AccessibilityPreferences& p){return p.interfaceScale>=0.75F&&p.interfaceScale<=2.0F;}
std::vector<std::string> ReleaseReadiness::onboardingSteps(){return {"Select MIDI input","Calibrate velocity","Select instrument","Confirm audio output","Open first book-linked lesson"};}
std::string ReleaseReadiness::exportBackup(const Backup& b){if(b.schemaVersion!=1||!validateAccessibility(b.accessibility))return{};std::ostringstream o;o<<"VLL_BACKUP\t1\nA\t"<<b.accessibility.highContrast<<'\t'<<b.accessibility.reducedMotion<<'\t'<<b.accessibility.screenReaderLabels<<'\t'<<b.accessibility.interfaceScale<<'\n';for(const auto&e:b.progress)o<<"P\t"<<e.conceptId<<'\t'<<e.competency<<'\t'<<e.evidenceCount<<'\n';return o.str();}
ImportResult ReleaseReadiness::importBackup(const std::string& s){ImportResult r;std::istringstream in(s);std::string line;if(!std::getline(in,line)||line!="VLL_BACKUP\t1"){r.error="Unsupported or corrupt backup header.";return r;}Backup b;bool access=false;while(std::getline(in,line)){std::istringstream row(line);std::string type;if(!std::getline(row,type,'\t'))continue;if(type=="A"){std::string h,m,l,n;if(!std::getline(row,h,'\t')||!std::getline(row,m,'\t')||!std::getline(row,l,'\t')||!std::getline(row,n)){r.error="Invalid accessibility record.";return r;}float scale=0;auto[z,en]=std::from_chars(n.data(),n.data()+n.size(),scale);if((h!="0"&&h!="1")||(m!="0"&&m!="1")||(l!="0"&&l!="1")||en!=std::errc{}||z!=n.data()+n.size()){r.error="Invalid accessibility record.";return r;}b.accessibility={h=="1",m=="1",l=="1",scale};access=true;}else if(type=="P"){ProgressEntry e;std::string c,n;if(!std::getline(row,e.conceptId,'\t')||!std::getline(row,c,'\t')||!std::getline(row,n)){r.error="Invalid progress record.";return r;}auto[a,ec]=std::from_chars(c.data(),c.data()+c.size(),e.competency);auto[z,en]=std::from_chars(n.data(),n.data()+n.size(),e.evidenceCount);if(ec!=std::errc{}||en!=std::errc{}||a!=c.data()+c.size()||z!=n.data()+n.size()||e.conceptId.empty()||e.competency<0||e.competency>4){r.error="Invalid progress record.";return r;}b.progress.push_back(e);}else{r.error="Unknown backup record.";return r;}}if(!access||!validateAccessibility(b.accessibility)){r.error="Backup accessibility settings are invalid.";return r;}r.backup=b;return r;}
}
